spring:
  profiles:
    active:
      - dev

---
server:
  port: 8001

spring:
  profiles: dev
  application:
    name: microservice-cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB01
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                 # 數據庫連接池的最小維持連接數
      initial-size: 5                             # 初始化連接數
      max-total: 5                                # 最大連接數
      max-wait-millis: 200                        # 等待連接獲取的最大超時時間
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka

info:
  app.name: microservicecloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001

spring:
  profiles: test
  application:
    name: microservice-cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloudDB02
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                 # 數據庫連接池的最小維持連接數
      initial-size: 5                             # 初始化連接數
      max-total: 5                                # 最大連接數
      max-wait-millis: 200                        # 等待連接獲取的最大超時時間
  jpa:
    show-sql: true

eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka

info:
  app.name: microservicecloud
  build.artifactId: $project.artifactId$
  build.version: $project.version$